export const UPDATE_LOCATION_LIKES_REQUEST = "UPDATE_LOCATION_LIKES_REQUEST";
export const UPDATE_LOCATION_LIKES_SUCCESS = "UPDATE_LOCATION_LIKES_SUCCESS";
export const UPDATE_LOCATION_LIKES_FAIL = "UPDATE_LOCATION_LIKES_FAIL";

export const GET_LOCATION_BY_ID_REQUEST = "GET_LOCATION_BY_ID_REQUEST";
export const GET_LOCATION_BY_ID_SUCCESS = "GET_LOCATION_BY_ID_SUCCESS";
export const GET_LOCATION_BY_ID_FAIL = "GET_LOCATION_BY_ID_FAIL";
