export const REPORTS_GET_REQUEST = "REPORTS_GET_REQUEST";
export const REPORTS_GET_SUCCESS = "REPORTS_GET_SUCCESS";
export const REPORTS_GET_FAIL = "REPORTS_GET_FAIL";

export const REPORT_GET_REQUEST = "REPORT_GET_REQUEST";
export const REPORT_GET_SUCCESS = "REPORT_GET_SUCCESS";
export const REPORT_GET_FAIL = "REPORT_GET_FAIL";

export const REPORTS_SUBMIT_REQUEST = "REPORTS_SUBMIT_REQUEST";
export const REPORTS_SUBMIT_SUCCESS = "REPORTS_SUBMIT_SUCCESS";
export const REPORTS_SUBMIT_FAIL = "REPORTS_SUBMIT_FAIL";
